name: Security Check with GitLeaks

on:
  push:
    branches:
      - main
    paths:
      - '**'   
  pull_request:
    branches:
      - main
    paths:
      - '**'   
  workflow_dispatch:
    inputs:
      name:
        description: 'Acionador manual do fluxo de trabalho'

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Executar o GitLeaks com Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/path \
            ghcr.io/gitleaks/gitleaks:latest detect \
            --source="/path" -v
